### ISSUE TITLE
pixel 7 build failed/ cannot install

### ISSUE THREAD

**Issue by HOCC2011** [AndroidIDEOfficial/AndroidIDE#1063]
### What happened?

My pixel 7 can't compile an apk and it says "Build failed"
I also tried to directly run the project, but Google play services keeps stopping and failed to install

### What's the expected behavior?

it should run and compile an apk

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by MarvinStelter** [comment]
Hi,
I also have an Pixel 7 and it works fine. 
Do you've an output which explains the error more/better?

**Comment by MarvinStelter** [comment]
Hm that is strange...

Your App is working when you manually start it?

Maybe Google Play Protect wants to start but can't and throws an error.

Maybe try to sign the app with the same key as in the play store version.

**Comment by MarvinStelter** [comment]
Edit: Normally Play Protect ask you if you want to install it anyways. Can you check if the version code has changed too?

**Comment by HOCC2011** [comment]
I tried again with building an apk using a new template ,but it still
failed.I also tried to run it , the google play store didn't crash like my
project (my project is imported from android studio)

在 2023年7月4日週二 15:46，CC HO ***@***.***> 寫道：

>
>   screen-20230704-153948.mp4
> <https://drive.google.com/file/d/1J_Po6jvyLMcvom2Y-CU-J8fduqMWGdWD/view?usp=drivesdk>
>
> Thanks for your reply! the following video shows that I compile my app.
> github.com/HOCC2011/Forget
>
> note:
> IDE version is 2.4.0 beta , I cleared all of its data and set it up again.
>
>
>

**Comment by HOCC2011** [comment]
I have checked it,but the app isn't installed

I tried again with building an apk using a new template ,but it still
failed.I also tried to run it , the google play store didn't crash

在 2023年7月4日週二 15:57，Marvin Stelter ***@***.***> 寫道：

**Comment by itsaky** [comment]
> I also tried to directly run the project, but Google play services keeps stopping and failed to install

If Play Protect blocks the installation, click on "More details" in the dialog and then click "Install anyway". This dialog is shown because the signature of the APK cannot be verified. This behavior is normal.

> <https://drive.google.com/file/d/1J_Po6jvyLMcvom2Y-CU-J8fduqMWGdWD/view?usp=drivesdk>

File is restricted.

> https://github.com/HOCC2011/Forget

This is your project, right? I tried to build this project and I'm able to build it successfully. This project's structure is bit different, please make sure you're opening the `Forget/Forget` folder in the IDE and not the root `Forget` folder.

For the installation issue, it seems like the IDE doesn't request the `REQUEST_INSTALL_PACKAGES` permission at all which might cause the IDE to show only the "Installing APK" message. However, you can manually grant this permission in your device's settings (look for "Install unknown apps" in app info).
