### ISSUE TITLE
Android Studio to this IDE

### ISSUE THREAD

**Issue by G8Victor** [AndroidIDEOfficial/AndroidIDE#1130]
### Feature description

Can we have the same xml file encoding to Android Studio?

I've ported my project from Android Studio to this ide (AndroidIDE)
this is the xml file in this ide
![Screenshot_20230719-120439](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/127200990/4991feb1-1682-4622-bb4d-0ccd302e3c84)

### What version of AndroidIDE you're using?

v2.5.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ThatMG393** [comment]
it should work, something is wrong with your xml

**Comment by G8Victor** [comment]
My process to port it in this ide is
- build a debudmg apk fom android studio
- extract it the apk content to my download directory
-  Then open a "recent project" from this ide
-  then use my extracted content

The app is working in android studio and the actual apk, the codes too, it opens up correctly, it uses the right encodiing

**Comment by BanDroid** [comment]
what you're opening in there was not xml file, instead it was encoded xml file (compiled resource file), since you mentioning you open a project from extracted debug application, that was not android project, instead it is a compiled packaged android app.

you cant open it in AndroidIDE, even Android Studio, what you need to do is you have to archive your android studio project, could be zip, rar, 7z, etc. and then extract the file and open it in AndroidIDE.

this issue should be closed since the author seems didn't understand how to properly open android project.

**Comment by G8Victor** [comment]
@BanDroid Oh ok. I will try that. Thank you for response
