### ISSUE TITLE
[Bug]: Unwanted auto insertion

### ISSUE THREAD

**Issue by gituser1000000** [AndroidIDEOfficial/AndroidIDE#1201]
### What happened?

Unwanted auto insertion

Example:
-Write:
new View.OnClickListener() {

-A closing curly brace is automatically added, and the cursor is now in between the braces. The auto completion popup also appears.

If we now press ENTER, we would see this:
new View.OnClickListener() {}/*
*
*/

It looks like a "block comment" snippet (which happens to be the first item on the auto completion list) has been added.

### What's the expected behavior?

It should show this after pressing ENTER:
new View.OnClickListener() {
    
}

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
The editor does not check whether the user is using a physical or virtual keyboard and selects the first completion item when `Enter` key is pressed. [Source](https://github.com/Rosemoe/sora-editor/blob/77372aaaf3a03aedb9247ce0a12f180601ca49cd/editor/src/main/java/io/github/rosemoe/sora/widget/EditorKeyEventHandler.java#L548).

However, this can be fixed in the IDE itself (by properly implementing the `select()` method in `EditorCompletionWindow`). I'll work on this later.

**Comment by gituser1000001** [comment]
It was actually nice to be able to just press enter for the first selection in most cases. It made auto completion faster to do without having to move your hand up to select an item. I know we need to pick the best way.

What do you think of the idea of leaving it as before but just not showing the auto completion popup when the user types pair characters such as (), {}, [], <>, ', ", ...  Why does it show the popup for those characters anyway when we don't even have a keyword or identifier that starts with one of those, right?
