### ISSUE TITLE
[Bug]: Invalid cursor placement after "Format code" action

### ISSUE THREAD

**Issue by gituser1000000** [AndroidIDEOfficial/AndroidIDE#1206]
### What happened?

Undoing a "Format code" (applying to a selection or the whole file) action places the cursor  all the way at the end of the file.

### What's the expected behavior?

The cursor should be right where it was before the code format.

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
I'll work on this later. Currently busy with something else.

**Comment by itsaky** [comment]
The IDE only formats the given input (selection or whole file), the [editor handles the content changes](https://github.com/Rosemoe/sora-editor/blob/3558f2fc68004c8f973ccbd3a1dc4239148999c1/editor/src/main/java/io/github/rosemoe/sora/widget/CodeEditor.java#L4669) after the formatting action. I think it would be better if this issue is reported in the [editor's repository](https://github.com/Rosemoe/sora-editor).

**Comment by Rosemoe** [comment]
It's actually because the editor does not record where the cursor is when text is changed. The cursor just shifts as primitive text actions(insert or delete) are performed.
I'll improve undo/redo experience in this case soon.

**Comment by itsaky** [comment]
Fixed in Rosemoe/sora-editor@8273b91d2aaa7f6799aa3e2c8767a60859fc43f8

**Comment by gituser1000000** [comment]
Great! Now we just need the copied text to get pasted correctly and we're golden :)
