### ISSUE TITLE
[Bug]: git and Gradle not in path in terminal.

### ISSUE THREAD

**Issue by frog-o** [AndroidIDEOfficial/AndroidIDE#1217]
### What happened?

Step to reproduce 
1. Open terminal
2.  Type git

Says git not found same for Gradle.

### What's the expected behavior?

I should be able to type in git command on the command line as well as Gradle I also filled this feature request

https://github.com/AndroidIDEOfficial/AndroidIDE/issues/1216

Wich says the terminal should be able to continue when the app is destroyed.

One of the things I wanted to do that you can not correctly is clone with depth 1.

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
`git` command is not installed by default. You can install it by executing `pkg install git` in the terminal.

When working with projects, you can use the Gradle Wrapper to execute Gradle commands from your project's root directory :

```bash
bash gradlew assembleDebug
```

Please note that you must execute the `gradlew` script with `bash`. This is because files in the shared storage do not have executable permissions (unless device is rooted).
