### ISSUE TITLE
[Bug]: Message "first build may take a while" does not appear when clear Gradle caches

### ISSUE THREAD

**Issue by Rafael2616** [AndroidIDEOfficial/AndroidIDE#1269]
### What happened?

 When clearing Gradle caches, I believe this message should appear in next build to inform the user that the build will take time 

### What's the expected behavior?

Show first build message when clearing Gradle caches

### What version of AndroidIDE you're using?

v2.5.2 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
We can only know if the Gradle caches were cleared if the user does so from the IDE preferences. If the user clears the caches using anything else, we won't know. If we check for the existence of the `caches` directory, we can never know if the caches were cleared even if the directory exists. This is because the user can simply delete the directories inside the `caches` directory.

If the user does clear the caches from IDE preferences, the message in the dialog already warns them about this issue.

If you think I missed anything or if you have a solution to this, please reopen this issue and we can discuss it further.

**Comment by Rafael2616** [comment]
I understand, actually thinking about just making the variable "isFirstBuild" to true when the user clicks on clear the cache, if he deletes it otherwise, I believe he doesn't need to handle it

**Comment by Rafael2616** [comment]
Thanks  ,you are correct
