### ISSUE TITLE
[Feature]: Enhancement Request: Interactive Parameter Info for Method Invocation in Android IDE.

### ISSUE THREAD

**Issue by sb-codz** [AndroidIDEOfficial/AndroidIDE#1477]
### Feature description

**Description:**
I am proposing a new feature to enhance the method invocation experience in Android IDEs. Currently, during method invocation, the "parameter info" or "parameter hints" feature displays parameter names alongside values. However, I believe there is an opportunity to introduce an interactive and user-friendly approach to make the process more intuitive.

**Proposed Enhancement:**
1. **Interactive Parameter Preview:** Introduce an interactive parameter preview functionality that dynamically updates as developers type method parameters. This feature would provide real-time feedback, allowing developers to see how the method invocation will look as they provide values.

2. **Visual Distinction:** Enhance the visual distinction between parameter names and values in the hints. Clear differentiation would contribute to a more straightforward understanding of the method invocation, reducing potential confusion.

3. **Customization Options:** Provide customization options in the IDE settings, allowing developers to personalize the appearance of parameter hints. This could include options for alignment, font size, and color, accommodating individual preferences.

**Use Case:**
The proposed feature aims to elevate the method invocation experience by introducing interactivity and improved visual clarity. Developers will benefit from a more intuitive process, reducing the likelihood of confusion and enhancing overall productivity.

**Additional Information:**
An interactive parameter preview is a valuable addition for Android IDEs, fostering a user-friendly environment for developers. This enhancement aligns with the goal of providing an efficient and enjoyable coding experience.
⛳Give A Milestone.
Thank you for considering this feature request.

---

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
When the cursor is within a method invocation, the "signature help" window shows the user the argument types for that method. It already does what it is expected to i.e. shows what type of argument the method accepts at the current parameter index.

**Comment by sb-codz** [comment]
That's right. But I think if this future is added then it will be very convenient for users to fix bugs. This will avoid mistakes while coding if Android Studio always shows argument info in the code editor. I hope I have understood you.

**Comment by gituser1000001** [comment]
Maybe the poster meant it should be "more" interactive with more details. Please allow me to try to list them out specifically.

1. The name of the param (if it was thoughtfully chosen) should be very valuable to the user as it would also let us know "what it is for". The hints don't give us this information currently.

2. Color mistyped params as we're typing so we instantly know instead of having to tap on the method name for the long and detailed info (which usually takes a few seconds to eye-ball out the signature of interest from sometimes a big wall of text popup)

3. Currently, the signature hints only appear right after a comma, then disapear or being covered by other error hints. This makes it a bit less interactive. I do understand continuously showing the signature hints might cover some other things, but maybe we could work something out.
