### ISSUE TITLE
[query]: why does AndroidIDE need so much storage?

### ISSUE THREAD

**Issue by Tanzin01** [AndroidIDEOfficial/AndroidIDE#1592]
The difference between termux and this app is quite big.

Termux requires only half the space .

**Comment by CyberXCoder-6649** [comment]
Termux functions as a terminal emulator, enabling users to access a Linux-like environment on Android. It primarily serves as a command-line interface, allowing execution of commands and installation of packages, resembling a traditional Linux terminal.

On the other hand, an Integrated Development Environment (IDE) like AndroidIDE is a comprehensive software suite designed for app development. It encompasses various tools, such as code editors, compilers, debuggers, and build automation systems. AndroidIDE provides an interface that streamlines the development process, offering features like code completion, project management, and testing capabilities, making it more user-friendly for creating Android applications.

**That's why Termux doesn't take up as much space as AndroidIDE does**

**Comment by Tanzin01** [comment]
Leaving out the editor part,  other parts were installed in termux(plus many others stuff which I use).

Currently, androidide is taking almost 10gb where termux is taking around 6gb.

There is a difference of 3-4 gb. Which is quite something.

A overview of what is taking which amount space- repot would be nice to know.

**Comment by CyberXCoder-6649** [comment]
> Leaving out the editor part, other parts were installed in termux(plus many others stuff which I use).
> 
> Currently, androidide is taking almost 10gb where termux is taking around 6gb.
> 
> There is a difference of 3-4 gb. Which is quite something.
> 
> A overview of what is taking which amount space- repot would be nice to know.

This includes project files, JDK, SDK, possibly NDK, command-line tools, build tools, multiple versions of NDK and SDK, and the fact that Gradle, not specifically designed for mobile, was implemented by AndroidIDE for Android usage. It's worth noting that AndroidIDE is still under development and will likely undergo further optimization in the future.

**Comment by arshiasahhamte** [comment]
I would like to thank all the supporters and sponsors for the new year. May it be a year full of light and happiness

**Comment by CyberXCoder-6649** [comment]
> I know very well because I had it, I deleted it because it got corrupted, now I'm asking you to download it

Just use this command in Terminal: idesetup -c

**Comment by itsaky** [comment]
The disk space used by AndroidIDE itself is not too much. Most of the space is used by JDK, Android SDK and the Gradle distributions.
