### ISSUE TITLE
[Bug]: colors.xml files are empty 

### ISSUE THREAD

**Issue by AmanRajAryan** [AndroidIDEOfficial/AndroidIDE#1626]
### What happened?

Color primary , color accent, red , green etc   are not present in default colors.xml

### What's the expected behavior?

It should be present

### What version of AndroidIDE you're using?

v2.6.0 (debug builds)

### Relevant log output

```shell
I'm using v2.7 beta from f-droid
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
> Color primary , color accent, red , green etc are not present in default colors.xml

The behavior is intentional. You can manually define colors in `res/values/colors.xml` and configure the application theme in `res/values/themes.xml`. Learn more about [color resources](https://developer.android.com/guide/topics/resources/more-resources#Color) and [theming](https://developer.android.com/develop/ui/views/theming/themes).
