### ISSUE TITLE
swipe functions clumsy in Android 12

### ISSUE THREAD

**Issue by StevanWhite** [AndroidIDEOfficial/AndroidIDE#1685]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

The UI invites us textually to swipe up, and right, to get a couple of functionalities.
Unfortunately, Android 12 uses right-swipe for "Back", and up-swipe for "Home", presenting a conflict.

The desired behavior does somehow occur -- perhaps if the text said "swipe the bottom bar up slowly and carefully",  it would be accurate.  But the result of right-swipe seems almost ... random: sometimes it tries to quit the app, sometimes I get a file tree.

### Expected behavior

Well, if I believe the textual notice, I expect AndroidIDE build tools to appear on swiping up, and a file tree to appear if I swipe right (the text says "swipe left", presumably meaning "swipe from the left")

But going by Android 12 behavior, right-swipe should go "back", and up-swipe should show all applications.

### Version name

v2.7.1-beta-armeabi-v7a

### Download source

GitHub

**Comment by itsaky** [comment]
Instead of the swipe actions, you can click to expand those views as well :

- Click on the bottom bar to expand the bottom sheet containing build output, logs and other things.
- To open the left drawer (for files, build variants, terminal and other options), you can click on the hamburger icon in the toolbar.

> the text says "swipe left", presumably meaning "swipe from the left"

Thanks, I have updated the text accordingly (for the bottom bar as well) in the above commit (5f11541).

This resolves the problems in my opinion. If not, feel free to re-open this issue with an explanation of what I missed.
