### ISSUE TITLE
Make storage permissions optional 

### ISSUE THREAD

**Issue by giiutfff** [AndroidIDEOfficial/AndroidIDE#1783]
### Issue Checklist

- [X] I confirm that this feature request has not been previously suggested.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that feature requests are subject to evaluation and may not be implemented immediately.
- [X] I agree to provide additional details if needed for a clearer understanding of the requested feature.

### Feature description

Make these permissions optional:
android.permission.READ_EXTERNAL_STORAGE
android.permission.WRITE_EXTERNAL_STORAGE
android.permission.MANAGE_EXTERNAL_STORAGE

### Use Case

Provide more protection while testing, reverse engineering malicious app.

### Benefits

Having access to all files might be less secure. Especially when testing some malicious code from Internet. Also Termux does not require these permissions mandatorily.

**Comment by itsaky** [comment]
Sorry for the late response.

These permissions are required because the projects are stored on the external storage. Even though AndroidIDE requests access to all files, it does not access any directory other than `/storage/emulated/0/AndroidIDEProjects`.

> Having access to all files might be less secure. Especially when testing some malicious code from Internet. 

Only AndroidIDE has access to the files, not the applications that are built with AndroidIDE (you'll need to grant permissions to those apps separately). The projects you build with AndroidIDE are totally your responsibility.
