### ISSUE TITLE
Extracting URL for Android SDK from manifest... jq: error: Could not open file /data/data/com.itsaky.androidide/files/home/manifest.json: No such file or directory  [Process completed (code 2) - press Enter]

### ISSUE THREAD

**Issue by blinlincom** [AndroidIDEOfficial/AndroidIDE#1825]
### Issue Checklist

- [X] I confirm that this issue is not a duplicate and hasn't been reported before.
- [X] I agree to follow the project's code of conduct.
- [X] I have checked and verified that I am using the latest version of AndroidIDE from GitHub or F-Droid.

### Additional terms

- [X] I understand that providing incomplete or inaccurate information may result in the issue being closed.
- [X] I agree to provide all requested details promptly for a comprehensive bug report.

### Issue explanation

Error reported during installation，Extracting URL for Android SDK from manifest...
jq: error: Could not open file /data/data/com.itsaky.androidide/files/home/manifest.json: No such file or directory

[Process completed (code 2) - press Enter]

### Expected behavior

Latest System
![Screenshot_2024-06-01-10-45-05-145_com itsaky androidide](https://github.com/AndroidIDEOfficial/AndroidIDE/assets/38490701/05ff72e7-8a05-4179-b796-4470ffdea91a)

### Version name

2.7.1

### Download source

GitHub

**Comment by itsakc-me** [comment]
@anthony-china listen this problem is not mainly related to AndroidIDE's issue, this could be happen because of your network can't stabilize connection with GitHub.

So make sure to first checkout if your network is perfect and if not then you could use a VPN or DNS to fix it.

So, onwards don't directly make a issue first fully understand by yourself and if you can't get it make sure to ask it in AndroidIDE telegram community and wait until seniors to give its solution and if the issue still persist then file a issue.
