### ISSUE TITLE
[FEATURE]: Support Build Variant for project

### ISSUE THREAD

**Issue by MrIkso** [AndroidIDEOfficial/AndroidIDE#223]
Hello, i found limitations in current tooling api realization, we don't support flavour and don't have any variant to build this project types, only debug/release.

**Comment by itsaky** [comment]
## For variants
We already have enough data about variants to allow the user to select which variant to build. We could get the list of variants from [`IdeAndroidModule`](https://github.com/itsaky/AndroidIDE/blob/main/build-tools/tooling-api-model/src/main/java/com/itsaky/androidide/tooling/api/model/IdeAndroidModule.kt). The [`SimpleArtifact`](https://github.com/itsaky/AndroidIDE/blob/main/build-tools/tooling-api-model/src/main/java/com/itsaky/androidide/tooling/api/messages/result/SimpleArtifact.kt) in [`SimpleVariantData`](https://github.com/itsaky/AndroidIDE/blob/main/build-tools/tooling-api-model/src/main/java/com/itsaky/androidide/tooling/api/messages/result/SimpleVariantData.kt) contains a field named `assembleTaskName` which is the task name that should be executed in order to build that variant.

## For product flavors
Well, it will take some time to be implemented. It may or may not need changes in the tooling API implementation.
