### ISSUE TITLE
Failed to connect to raw.githubusercontent.com port 443

### ISSUE THREAD

**Issue by kuttahaitu** [AndroidIDEOfficial/AndroidIDE#651]
### Feature description

When I try to setup build tools in terminal it's showing 
curl: (28) Failed to connect to raw.githubusercontent.com port 443 after 31631 ms: Couldn't connect to server

Even my connection speed is working fine. 

### What version of AndroidIDE you're using?

v2.1.3 (debug builds)

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itsaky** [comment]
This issue is definitely not a feature request. Use proper issue templates when creating new issues.

> curl: (28) Failed to connect to raw.githubusercontent.com port 443 after 31631 ms: Couldn't connect to server

The error clearly says that the connection timed out (error code: `28`). See [cURL error codes](https://curl.se/libcurl/c/libcurl-errors.html). So, the issue might be with your internet connection or your connection settings.

As you're trying to install the build tools, you could try to install them manually, that is, without the `idesetup` command. See [this Telegram message](https://t.me/androidide_discussions/60877).
