### ISSUE TITLE
[Bug]:virus apk in miui

### ISSUE THREAD

**Issue by Booklight12** [AndroidIDEOfficial/AndroidIDE#948]
### What happened?

Here's an interesting question, why was it reported as a virus by miui.and I'm just exporting the example project

### What's the expected behavior?

null

### What version of AndroidIDE you're using?

v2.4.0 (debug builds)

### Relevant log output

```shell
Not applicable
```

### Duplicate issues

- [X] This issue has not been reported yet.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Booklight12** [comment]
![Screenshot_2023-04-16-15-16-03-811_com miui packageinstaller](https://user-images.githubusercontent.com/64678717/232280279-eab66835-dc8e-4528-aa6a-b1d1f1e9a7e0.jpg)
like this

**Comment by itsaky** [comment]
That error may be shown because of the signing key used to sign the application or due to any other components you may have included in your application.

To clarify, AndroidIDE does not add any malicious components to your application. The only thing it adds is `LogSender` which is used to show logs from your application in AndroidIDE.
